/**
 * Owns manifests, registries, hook emission, capabilities, trust, generations, and plugin loading.
 * It exists to add behavior through plugins without leaking those concerns into the kernel.
 */
export const pluginsPackage = "@peye/plugins";

export {
  type CapabilityGrants,
  CapabilityNameSchema,
  createCapabilityGrants,
  grantedCapabilities,
  hasCapability,
  missingCapabilities,
} from "./capability.js";
export {
  type AnyToolDeclaration,
  type CommandContribution,
  type CommandDeclaration,
  type CommandExecutionContext,
  type Contribution,
  type ContributionKey,
  contributionKey,
  defineCommandContribution,
  defineContribution,
  defineHookContribution,
  defineInstructionFragmentContribution,
  defineToolContribution,
  type HookContribution,
  type HookDeclaration,
  type HookExecute,
  type HookMergeClass,
  type InstructionFragmentContribution,
  type InstructionFragmentDeclaration,
  type RegisteredContribution,
  type ToolContribution,
  ToolContributionError,
  type ToolDeclaration,
  type ToolExecutionContext,
  type ToolExecutionMode,
  type ToolExecutionResult,
  type ToolReplay,
} from "./contribution.js";
export {
  DEFAULT_GATE_TIMEOUT_MILLIS,
  DEFAULT_TAP_QUEUE_CAPACITY,
  type HookContributionSkippedDiagnostic,
  type HookDiagnostic,
  HookEmitter,
  HookEmitterLive,
  type HookEmitterOptions,
  type HookEmitterService,
  type HookGateRejectedDiagnostic,
  type HookTapDroppedDiagnostic,
  type HookTapFailedDiagnostic,
} from "./emitter.js";
export {
  ContributionRegistryError,
  type ContributionRegistryErrorReason,
  GateRejected,
  type PluginLoadCause,
  PluginLoadError,
} from "./errors.js";
export {
  type CompactionGateHookInput,
  CompactionGateHookInputSchema,
  type CompactionGateHookOutput,
  CompactionGateHookOutputSchema,
  type ContextHookInput,
  ContextHookInputSchema,
  type ContextHookOutput,
  ContextHookOutputSchema,
  defineHookPoint,
  HOOK_POINT_NAMES,
  HOOK_POINTS,
  type HookFailurePolicy,
  type HookPayload,
  type HookPointDefinition,
  type HookPointInput,
  type HookPointName,
  type HookPointOutput,
  type HookPointTypeMap,
  type InputHandlingHookInput,
  InputHandlingHookInputSchema,
  type InputHandlingHookOutput,
  InputHandlingHookOutputSchema,
  type InputTransformHookInput,
  InputTransformHookInputSchema,
  type InputTransformHookOutput,
  InputTransformHookOutputSchema,
  type ProgressHookInput,
  ProgressHookInputSchema,
  type ProgressHookOutput,
  ProgressHookOutputSchema,
  type ProviderRequestHookInput,
  ProviderRequestHookInputSchema,
  type ProviderRequestHookOutput,
  ProviderRequestHookOutputSchema,
  type ResourceDiscoveryHookInput,
  ResourceDiscoveryHookInputSchema,
  type ResourceDiscoveryHookOutput,
  ResourceDiscoveryHookOutputSchema,
  type SessionLifecycleHookInput,
  SessionLifecycleHookInputSchema,
  type SessionLifecycleHookOutput,
  SessionLifecycleHookOutputSchema,
  type ToolCallGateHookInput,
  ToolCallGateHookInputSchema,
  type ToolCallGateHookOutput,
  ToolCallGateHookOutputSchema,
  type ToolResultHookInput,
  ToolResultHookInputSchema,
  type ToolResultHookOutput,
  ToolResultHookOutputSchema,
  type TrustHookInput,
  TrustHookInputSchema,
  type TrustHookOutput,
  TrustHookOutputSchema,
  type TurnLifecycleHookInput,
  TurnLifecycleHookInputSchema,
  type TurnLifecycleHookOutput,
  TurnLifecycleHookOutputSchema,
} from "./hook-points.js";
export {
  type CapabilityDeclaration,
  CapabilityDeclarationSchema,
  ContributionNameSchema,
  decodePluginManifest,
  MAX_NAME_SEGMENT_LENGTH,
  type PluginManifest,
  PluginManifestSchema,
  PluginNameSchema,
} from "./manifest.js";
export {
  CommandContributionKind,
  type ContributionConflictDiagnostic,
  type ContributionKind,
  ContributionRegistry,
  ContributionRegistryLive,
  type ContributionRegistryOptions,
  type ContributionRegistryService,
  type ContributionUnavailableDiagnostic,
  defineContributionKind,
  HookContributionKind,
  InstructionFragmentContributionKind,
  type KindRegistrationConflictDiagnostic,
  type RegistryDiagnostic,
  ToolContributionKind,
} from "./registry.js";
