/**
 * Owns manifests, registries, hook emission, capabilities, trust, generations, and plugin loading.
 * It exists to add behavior through plugins without leaking those concerns into the kernel.
 */
export const pluginsPackage = "@pop-eye/plugins";

export {
  type CapabilityGrants,
  CapabilityNameSchema,
  createCapabilityGrants,
  grantedCapabilities,
  hasCapability,
  missingCapabilities,
} from "./capability.js";
export {
  type AnyToolDeclaration,
  type CommandCompactionResult,
  type CommandContribution,
  type CommandDeclaration,
  type CommandExecutionContext,
  type Contribution,
  type ContributionKey,
  contributionKey,
  defineCommandContribution,
  defineContribution,
  defineHookContribution,
  defineInstructionFragmentContribution,
  defineToolContribution,
  type HookContribution,
  type HookDeclaration,
  type HookExecute,
  type HookMergeClass,
  type InstructionFragmentContribution,
  type InstructionFragmentDeclaration,
  type RegisteredContribution,
  type ToolContribution,
  ToolContributionError,
  type ToolDeclaration,
  type ToolExecutionContext,
  type ToolExecutionMode,
  type ToolExecutionResult,
  type ToolReplay,
} from "./contribution.js";
export {
  classifyResolvedPluginSource,
  type PluginDigestLimits,
  type PluginDiscoveryConfig,
  PluginDiscoveryError,
  type PluginSource,
  type PluginSourceOrigin,
  type PluginSourceScope,
  phase1Sources,
  phase2ExecutionSources,
  phase2Sources,
  type TrustDecisionForDiscovery,
} from "./discovery.js";
export {
  DEFAULT_GATE_TIMEOUT_MILLIS,
  DEFAULT_HOOK_TIMEOUT_MILLIS,
  DEFAULT_TAP_QUEUE_CAPACITY,
  type HookContributionSkippedDiagnostic,
  type HookDiagnostic,
  type HookEmitError,
  HookEmitter,
  HookEmitterLive,
  type HookEmitterOptions,
  type HookEmitterService,
  type HookErrorPayload,
  type HookFieldConflictDiagnostic,
  type HookGateRejectedDiagnostic,
  type HookPriorityTieDiagnostic,
  type HookTapDroppedDiagnostic,
  type HookTapFailedDiagnostic,
} from "./emitter.js";
export {
  ContributionRegistryError,
  type ContributionRegistryErrorReason,
  GateRejected,
  HookInputInvalid,
  type PluginLoadCause,
  PluginLoadError,
  TrustResolverTimeoutError,
} from "./errors.js";
export type {
  GenerationLoadError as GenerationLoadErrorLegacy,
  GenerationPlugin as GenerationPluginLegacy,
  GenerationSwapDiagnostic as GenerationSwapDiagnosticLegacy,
  LoadGenerationOptions as LoadGenerationOptionsLegacy,
  PluginGeneration as PluginGenerationLegacy,
  PluginRuntime,
  PluginRuntime as PluginRuntimeLegacy,
  PluginRuntimeDebugInfo as PluginRuntimeDebugInfoLegacy,
} from "./generation.js";
export { makePluginRuntime } from "./generation.js";
export type {
  GenerationLease,
  GenerationLoadError,
  GenerationPlugin,
  GenerationRuntime,
  GenerationSwapDiagnostic,
  LoadGenerationOptions,
  PluginGeneration,
  PluginRuntimeDebugInfo,
  TrustResolutionRequest,
  TrustResolver,
} from "./generation-runtime.js";
export {
  DEFAULT_IMPORT_TIMEOUT_MILLIS,
  DEFAULT_TRUST_RESOLVER_TIMEOUT_MILLIS,
  GenerationBusyError,
  GenerationDrainTimeoutError,
  loadGeneration,
  makeGenerationRuntime,
  makeGenerationRuntimeWithLoader,
} from "./generation-runtime.js";
export {
  type CompactionGateHookInput,
  CompactionGateHookInputSchema,
  type CompactionGateHookOutput,
  CompactionGateHookOutputSchema,
  type CompactionGateResult,
  CompactionGateResultSchema,
  type ContextHookInput,
  ContextHookInputSchema,
  type ContextHookOutput,
  ContextHookOutputSchema,
  defineHookPoint,
  HOOK_POINT_NAMES,
  HOOK_POINTS,
  type HookFailurePolicy,
  type HookPayload,
  type HookPointDefinition,
  type HookPointInput,
  type HookPointName,
  type HookPointOutput,
  type HookPointResult,
  type HookPointTypeMap,
  type InputHandlingHookInput,
  InputHandlingHookInputSchema,
  type InputHandlingHookOutput,
  InputHandlingHookOutputSchema,
  type InputHandlingResult,
  InputHandlingResultSchema,
  type InputTransformHookInput,
  InputTransformHookInputSchema,
  type InputTransformHookOutput,
  InputTransformHookOutputSchema,
  type ProgressHookInput,
  ProgressHookInputSchema,
  type ProgressHookOutput,
  ProgressHookOutputSchema,
  type ProviderRequestHookInput,
  ProviderRequestHookInputSchema,
  type ProviderRequestHookOutput,
  ProviderRequestHookOutputSchema,
  type ResourceDiscoveryHookInput,
  ResourceDiscoveryHookInputSchema,
  type ResourceDiscoveryHookOutput,
  ResourceDiscoveryHookOutputSchema,
  type SessionLifecycleHookInput,
  SessionLifecycleHookInputSchema,
  type SessionLifecycleHookOutput,
  SessionLifecycleHookOutputSchema,
  type ToolCallGateHookInput,
  ToolCallGateHookInputSchema,
  type ToolCallGateHookOutput,
  ToolCallGateHookOutputSchema,
  type ToolCallGateResult,
  ToolCallGateResultSchema,
  type ToolResultHookInput,
  ToolResultHookInputSchema,
  type ToolResultHookOutput,
  ToolResultHookOutputSchema,
  TrustChangeSummarySchema,
  type TrustHookInput,
  TrustHookInputSchema,
  type TrustHookOutput,
  TrustHookOutputSchema,
  type TrustResult,
  TrustResultSchema,
  type TurnLifecycleHookInput,
  TurnLifecycleHookInputSchema,
  type TurnLifecycleHookOutput,
  TurnLifecycleHookOutputSchema,
} from "./hook-points.js";
export {
  CurrentGrantsFiberRef,
  CurrentPluginFiberRef,
  DEFAULT_INTERACTION_TIMEOUT_MILLIS,
  makePluginInteractionsLiveLayer,
  makePluginInteractionsLiveService,
  makePluginInteractionsNullService,
  type PluginInteractionRequest,
  type PluginInteractionResolution,
  PluginInteractions,
  PluginInteractionsNullLive,
  type PluginInteractionsService,
} from "./interactions.js";
export type { LoadedPlugin, PluginModuleLoadOptions } from "./loader.js";
export { loadPluginModule } from "./loader.js";
export {
  type CapabilityDeclaration,
  CapabilityDeclarationSchema,
  ContributionNameSchema,
  decodePluginManifest,
  MAX_NAME_SEGMENT_LENGTH,
  type PluginManifest,
  PluginManifestSchema,
  PluginNameSchema,
} from "./manifest.js";
export {
  CommandContributionKind,
  type ContributionConflictDiagnostic,
  type ContributionKind,
  ContributionRegistry,
  ContributionRegistryLive,
  type ContributionRegistryOptions,
  type ContributionRegistryService,
  type ContributionUnavailableDiagnostic,
  defineContributionKind,
  HookContributionKind,
  InstructionFragmentContributionKind,
  type KindRegistrationConflictDiagnostic,
  type RegistryDiagnostic,
  ToolContributionKind,
} from "./registry.js";
export {
  checkTrust,
  type PluginFileDigest,
  recordDecision,
  revokeTrust,
  type TrustChangeSummary,
  type TrustCheckOptions,
  type TrustCheckResult,
  type TrustDecision,
  type TrustDecisionProvenance,
  type TrustDiagnostic,
  type TrustRecord,
  TrustStore,
  TrustStoreError,
  type TrustStoreErrorReason,
  TrustStoreLive,
  type TrustStoreLiveOptions,
  TrustStoreMemory,
  type TrustStoreService,
} from "./trust.js";
export {
  DEFAULT_PLUGIN_DIGEST_MAX_FILE_COUNT,
  DEFAULT_PLUGIN_DIGEST_MAX_TOTAL_BYTES,
  type PluginDigestDiagnostic,
  PluginDigestError,
  type PluginDigestViolation,
  type ProjectPluginDigest,
} from "./trust-digest.js";
